name: very_good_weather
description: Flutter application which gives users the ability to look up the weather for any location. Coding challenge for VGV by long1eu
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  built_value: ^7.1.0
  built_collection: ^4.3.2
  chopper: ^3.0.3
  flutter_redux: ^0.6.0
  freezed_annotation: ^0.11.0
  intl: ^0.16.1
  http: ^0.12.2
  meta: ^1.2.2
  redux: ^4.0.0+3
  redux_epics: ^0.14.0
  rxdart: ^0.24.1
  flutter_svg: ^0.18.0
  smooth_page_indicator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  chopper_generator: ^3.0.5
  freezed: ^0.11.4

flutter:
  uses-material-design: true
  assets:
    - res/svg/